/**
 * Settings screen.
 *
 * Audio and accessibility preferences, the control guide, and progress
 * management. Every change is written to the save file immediately, so settings
 * survive a refresh without an explicit "apply" step.
 */

import { useState } from 'react';
import { Button } from '../components/ui/Button.tsx';
import { Modal } from '../components/ui/Modal.tsx';
import { ScreenFrame } from '../components/ui/ScreenFrame.tsx';
import { audioManager } from '../systems/audio/audioManager.ts';
import { CONTROL_GUIDE } from '../systems/input/inputManager.ts';
import { useGameStore } from '../state/gameStore.ts';

interface SwitchProps {
  readonly label: string;
  readonly hint?: string;
  readonly checked: boolean;
  readonly onChange: (value: boolean) => void;
  readonly testId?: string;
}

function SettingSwitch({ label, hint, checked, onChange, testId }: SwitchProps) {
  return (
    <div className="setting-row">
      <span className="setting-row__label">
        {label}
        {hint ? <span className="setting-row__hint">{hint}</span> : null}
      </span>
      <button
        type="button"
        role="switch"
        aria-checked={checked}
        aria-label={label}
        className="switch"
        data-testid={testId}
        onClick={() => {
          audioManager.play('menu-select');
          onChange(!checked);
        }}
      >
        <span className="switch__pip" aria-hidden="true" />
        {checked ? 'On' : 'Off'}
      </button>
    </div>
  );
}

interface SliderProps {
  readonly label: string;
  readonly value: number;
  readonly onChange: (value: number) => void;
  readonly disabled?: boolean;
  readonly testId?: string;
}

function VolumeSlider({ label, value, onChange, disabled = false, testId }: SliderProps) {
  const percent = Math.round(value * 100);
  return (
    <div className="setting-row">
      <span className="setting-row__label">
        {label}
        <span className="setting-row__hint">{percent}%</span>
      </span>
      <input
        className="slider"
        type="range"
        min={0}
        max={100}
        step={5}
        value={percent}
        disabled={disabled}
        aria-label={label}
        data-testid={testId}
        onChange={(event) => onChange(Number(event.target.value) / 100)}
      />
    </div>
  );
}

export function SettingsScreen() {
  const audio = useGameStore((state) => state.audio);
  const accessibility = useGameStore((state) => state.accessibility);
  const saveStatus = useGameStore((state) => state.saveStatus);
  const savePersisting = useGameStore((state) => state.savePersisting);
  const setAudioSettings = useGameStore((state) => state.setAudioSettings);
  const setReducedMotion = useGameStore((state) => state.setReducedMotion);
  const closeSettings = useGameStore((state) => state.closeSettings);
  const resetProgress = useGameStore((state) => state.resetProgress);

  const [confirmReset, setConfirmReset] = useState(false);
  const muted = !audio.masterEnabled;

  return (
    <ScreenFrame
      eyebrow="Options"
      title="Settings"
      showSettings={false}
      footer={
        <Button variant="primary" onClick={closeSettings} sound="menu-back" data-testid="settings-back">
          Back
        </Button>
      }
    >
      <div className="settings-grid">
        <section className="panel" aria-labelledby="settings-audio">
          <p className="panel__eyebrow">Sound</p>
          <h2 className="panel__title" id="settings-audio">
            Audio
          </h2>
          <p className="subtle">
            All music and effects in this build are generated by the game at runtime. There are no audio
            files, and no external audio is downloaded.
          </p>

          <div style={{ marginTop: 'var(--space-3)' }}>
            <SettingSwitch
              label="Master audio"
              hint="Turns all game sound on or off"
              checked={audio.masterEnabled}
              onChange={(value) => setAudioSettings({ masterEnabled: value })}
              testId="setting-master"
            />
            <SettingSwitch
              label="Background music"
              checked={audio.musicEnabled}
              onChange={(value) => setAudioSettings({ musicEnabled: value })}
              testId="setting-music"
            />
            <SettingSwitch
              label="Sound effects"
              checked={audio.sfxEnabled}
              onChange={(value) => setAudioSettings({ sfxEnabled: value })}
              testId="setting-sfx"
            />
            <VolumeSlider
              label="Music volume"
              value={audio.musicVolume}
              disabled={muted || !audio.musicEnabled}
              onChange={(value) => setAudioSettings({ musicVolume: value })}
              testId="setting-music-volume"
            />
            <VolumeSlider
              label="Sound-effects volume"
              value={audio.sfxVolume}
              disabled={muted || !audio.sfxEnabled}
              onChange={(value) => {
                setAudioSettings({ sfxVolume: value });
                audioManager.play('menu-move');
              }}
              testId="setting-sfx-volume"
            />
          </div>

          {audioManager.unsupported ? (
            <p className="subtle" style={{ marginTop: 'var(--space-3)' }}>
              This browser does not provide Web Audio, so the game is running silently. Everything else
              works normally.
            </p>
          ) : null}
        </section>

        <section className="panel" aria-labelledby="settings-access">
          <p className="panel__eyebrow">Comfort</p>
          <h2 className="panel__title" id="settings-access">
            Accessibility
          </h2>
          <SettingSwitch
            label="Reduce motion"
            hint="Suppresses non-essential animation and transitions"
            checked={accessibility.reducedMotion}
            onChange={setReducedMotion}
            testId="setting-reduced-motion"
          />
          <p className="subtle" style={{ marginTop: 'var(--space-3)' }}>
            Every control is reachable with the Tab key and shows a visible focus ring. Progress,
            stamina and objective states are always communicated with text as well as colour. Features
            not yet implemented are listed in the project’s known-limitations register.
          </p>
        </section>

        <section className="panel" aria-labelledby="settings-controls">
          <p className="panel__eyebrow">Reference</p>
          <h2 className="panel__title" id="settings-controls">
            Controls
          </h2>
          <table className="control-table">
            <thead>
              <tr>
                <th scope="col">Key</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {CONTROL_GUIDE.map((entry) => (
                <tr key={entry.keys}>
                  <td>{entry.keys}</td>
                  <td>{entry.action}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <section className="panel" aria-labelledby="settings-data">
          <p className="panel__eyebrow">Saved data</p>
          <h2 className="panel__title" id="settings-data">
            Progress
          </h2>
          <p className="subtle">
            Progress and settings are stored in this browser only. No personal information is saved and
            nothing is sent anywhere.
          </p>
          <p className="text-small" style={{ marginTop: 'var(--space-3)' }} data-testid="save-status">
            Save status: <strong>{describeSaveStatus(saveStatus, savePersisting)}</strong>
          </p>
          <div style={{ marginTop: 'var(--space-4)' }}>
            <Button onClick={() => setConfirmReset(true)} data-testid="reset-progress">
              Reset progress
            </Button>
          </div>
        </section>
      </div>

      <Modal open={confirmReset} title="Reset all progress?" onClose={() => setConfirmReset(false)}>
        <p className="muted">
          This clears your selected club, your selected fighter and all training progress. Your audio and
          accessibility settings are kept. This cannot be undone.
        </p>
        <div className="modal__actions">
          <Button
            variant="primary"
            data-testid="confirm-reset"
            onClick={() => {
              setConfirmReset(false);
              resetProgress();
            }}
          >
            Reset progress
          </Button>
          <Button variant="ghost" sound="menu-back" onClick={() => setConfirmReset(false)}>
            Cancel
          </Button>
        </div>
      </Modal>
    </ScreenFrame>
  );
}

function describeSaveStatus(status: string, persisting: boolean): string {
  if (!persisting) return 'Not saving — this browser rejected the write';
  switch (status) {
    case 'loaded':
      return 'Loaded from this browser';
    case 'empty':
      return 'New save';
    case 'migrated':
      return 'Upgraded from an earlier version';
    case 'recovered':
      return 'Recovered after unreadable data';
    case 'unavailable':
      return 'Unavailable — progress will not persist';
    default:
      return status;
  }
}
