/**
 * Procedural sound synthesis.
 *
 * Every sound in this game is generated at runtime with the Web Audio API.
 * There are no audio files in the repository, which means there is no sample
 * licensing to track and nothing to attribute: all output is original,
 * generated by the code below. See `docs/ASSET_REGISTER.md`.
 *
 * These helpers are pure signal-generation utilities. Routing, volume and
 * enable/disable live in `audioManager.ts`.
 */

/** Identifiers for every sound effect the game can request. */
export type SfxName =
  | 'menu-move'
  | 'menu-select'
  | 'menu-back'
  | 'training-success'
  | 'light-impact'
  | 'strong-impact'
  | 'block'
  | 'dodge'
  | 'footstep'
  | 'exhausted'
  | 'telegraph'
  | 'tutorial-complete'
  | 'applause'
  | 'victory';

/**
 * Builds a short burst of filtered white noise, reused for impacts, footsteps
 * and applause. Cached by the manager because buffer creation is not free.
 */
export function createNoiseBuffer(context: BaseAudioContext, seconds: number): AudioBuffer {
  const length = Math.max(1, Math.floor(context.sampleRate * seconds));
  const buffer = context.createBuffer(1, length, context.sampleRate);
  const data = buffer.getChannelData(0);
  // Deterministic pseudo-random sequence: identical every run, so the sound of
  // the game never changes between sessions.
  let seed = 0x2f6e2b1;
  for (let i = 0; i < length; i += 1) {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    data[i] = (seed / 0x3fffffff - 1) * 0.9;
  }
  return buffer;
}

interface ToneOptions {
  readonly type: OscillatorType;
  readonly frequency: number;
  /** Optional target frequency; the oscillator glides to it over `duration`. */
  readonly glideTo?: number;
  readonly duration: number;
  readonly gain: number;
  readonly attack?: number;
  readonly startAt?: number;
}

/** Schedules a single enveloped oscillator tone into `destination`. */
export function playTone(
  context: AudioContext,
  destination: AudioNode,
  options: ToneOptions,
): void {
  const start = options.startAt ?? context.currentTime;
  const attack = options.attack ?? 0.008;
  const oscillator = context.createOscillator();
  const envelope = context.createGain();

  oscillator.type = options.type;
  oscillator.frequency.setValueAtTime(options.frequency, start);
  if (options.glideTo !== undefined) {
    oscillator.frequency.exponentialRampToValueAtTime(
      Math.max(20, options.glideTo),
      start + options.duration,
    );
  }

  envelope.gain.setValueAtTime(0.0001, start);
  envelope.gain.exponentialRampToValueAtTime(Math.max(0.0002, options.gain), start + attack);
  envelope.gain.exponentialRampToValueAtTime(0.0001, start + options.duration);

  oscillator.connect(envelope);
  envelope.connect(destination);
  oscillator.start(start);
  oscillator.stop(start + options.duration + 0.02);
}

interface NoiseOptions {
  readonly buffer: AudioBuffer;
  readonly duration: number;
  readonly gain: number;
  readonly filterType: BiquadFilterType;
  readonly frequency: number;
  /** Optional target filter frequency, swept over `duration`. */
  readonly sweepTo?: number;
  readonly q?: number;
  readonly startAt?: number;
}

/** Schedules a filtered, enveloped noise burst into `destination`. */
export function playNoise(
  context: AudioContext,
  destination: AudioNode,
  options: NoiseOptions,
): void {
  const start = options.startAt ?? context.currentTime;
  const source = context.createBufferSource();
  const filter = context.createBiquadFilter();
  const envelope = context.createGain();

  source.buffer = options.buffer;
  source.loop = options.buffer.duration < options.duration;

  filter.type = options.filterType;
  filter.frequency.setValueAtTime(options.frequency, start);
  if (options.sweepTo !== undefined) {
    filter.frequency.exponentialRampToValueAtTime(
      Math.max(40, options.sweepTo),
      start + options.duration,
    );
  }
  filter.Q.value = options.q ?? 1;

  envelope.gain.setValueAtTime(0.0001, start);
  envelope.gain.exponentialRampToValueAtTime(Math.max(0.0002, options.gain), start + 0.006);
  envelope.gain.exponentialRampToValueAtTime(0.0001, start + options.duration);

  source.connect(filter);
  filter.connect(envelope);
  envelope.connect(destination);
  source.start(start);
  source.stop(start + options.duration + 0.02);
}

/**
 * Renders one sound effect. Kept as a single switch so the full sound palette
 * of the game is readable in one place.
 */
export function renderSfx(
  context: AudioContext,
  destination: AudioNode,
  name: SfxName,
  noise: AudioBuffer,
): void {
  const now = context.currentTime;

  switch (name) {
    case 'menu-move':
      playTone(context, destination, { type: 'triangle', frequency: 620, duration: 0.07, gain: 0.16 });
      break;

    case 'menu-select':
      playTone(context, destination, { type: 'triangle', frequency: 520, duration: 0.09, gain: 0.2 });
      playTone(context, destination, {
        type: 'triangle',
        frequency: 780,
        duration: 0.13,
        gain: 0.16,
        startAt: now + 0.05,
      });
      break;

    case 'menu-back':
      playTone(context, destination, {
        type: 'triangle',
        frequency: 420,
        glideTo: 260,
        duration: 0.14,
        gain: 0.16,
      });
      break;

    case 'training-success':
      // Rising perfect fifth: unmistakably positive, short enough to repeat.
      playTone(context, destination, { type: 'sine', frequency: 660, duration: 0.12, gain: 0.2 });
      playTone(context, destination, {
        type: 'sine',
        frequency: 990,
        duration: 0.22,
        gain: 0.18,
        startAt: now + 0.09,
      });
      break;

    case 'light-impact':
      // A canvas/gi snap: brief, bright, no low end.
      playNoise(context, destination, {
        buffer: noise,
        duration: 0.09,
        gain: 0.24,
        filterType: 'bandpass',
        frequency: 2100,
        sweepTo: 900,
        q: 1.1,
      });
      break;

    case 'strong-impact':
      playNoise(context, destination, {
        buffer: noise,
        duration: 0.17,
        gain: 0.3,
        filterType: 'bandpass',
        frequency: 1400,
        sweepTo: 320,
        q: 0.9,
      });
      playTone(context, destination, {
        type: 'sine',
        frequency: 150,
        glideTo: 70,
        duration: 0.2,
        gain: 0.24,
      });
      break;

    case 'block':
      playNoise(context, destination, {
        buffer: noise,
        duration: 0.11,
        gain: 0.22,
        filterType: 'lowpass',
        frequency: 900,
        sweepTo: 320,
      });
      playTone(context, destination, { type: 'square', frequency: 220, duration: 0.07, gain: 0.1 });
      break;

    case 'dodge':
      // Cloth-and-air sweep.
      playNoise(context, destination, {
        buffer: noise,
        duration: 0.22,
        gain: 0.14,
        filterType: 'bandpass',
        frequency: 600,
        sweepTo: 2600,
        q: 0.7,
      });
      break;

    case 'footstep':
      playNoise(context, destination, {
        buffer: noise,
        duration: 0.06,
        gain: 0.09,
        filterType: 'lowpass',
        frequency: 480,
      });
      break;

    case 'exhausted':
      playTone(context, destination, {
        type: 'sawtooth',
        frequency: 200,
        glideTo: 120,
        duration: 0.18,
        gain: 0.1,
      });
      break;

    case 'telegraph':
      playTone(context, destination, { type: 'sine', frequency: 880, duration: 0.08, gain: 0.11 });
      break;

    case 'tutorial-complete':
      // Ascending pentatonic flourish.
      [523.25, 587.33, 698.46, 880].forEach((frequency, index) => {
        playTone(context, destination, {
          type: 'triangle',
          frequency,
          duration: 0.3,
          gain: 0.18,
          startAt: now + index * 0.11,
        });
      });
      break;

    case 'applause': {
      // Layered noise bursts at irregular offsets read as a crowd rather than
      // as a single hiss. Deterministic offsets keep it identical every time.
      const offsets = [0, 0.03, 0.07, 0.11, 0.16, 0.22, 0.29, 0.37, 0.46, 0.56];
      offsets.forEach((offset, index) => {
        playNoise(context, destination, {
          buffer: noise,
          duration: 0.9 - index * 0.05,
          gain: 0.07,
          filterType: 'bandpass',
          frequency: 1800 + index * 90,
          sweepTo: 900,
          q: 0.6,
          startAt: now + offset,
        });
      });
      break;
    }

    case 'victory':
      [523.25, 659.25, 783.99, 1046.5].forEach((frequency, index) => {
        playTone(context, destination, {
          type: 'triangle',
          frequency,
          duration: 0.55,
          gain: 0.17,
          startAt: now + index * 0.14,
        });
      });
      break;
  }
}
